apiVersion: apps/v1
kind: Deployment
metadata:
  name: accountingcontrol
  namespace: "proj-gr4"
  labels:
    app: accountingcontrol
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accountingcontrol
  template:
    metadata:
      labels:
        app: accountingcontrol
    spec:
      containers:
      - name: accountingcontrol
        image: mortenlyngosenquist/accountingcontrol:latest
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata: 
  name: accountingcontrol
  namespace: "proj-gr4"
  labels:
    app: accountingcontrol
spec:
  selector:
    app: accountingcontrol
  ports:
    - port: 8080
      targetPort: 80
    
      
      
