apiVersion: apps/v1
kind: Deployment
metadata:
  name: accountingcontrol
  namespace: "proj-gr4"
  labels:
    app: accountingcontrol
spec:
  replicas: 2
  selector:
    matchLabels:
      app: accountingcontrol
  template:
    metadata:
      labels:
        app: accountingcontrol
    spec:
      containers:
      - name: accountingcontrol
        image: mortenlyngosenquist/accountingcontrol:latest
---
apiVersion: v1
kind: Service
metadata: 
  name: accountingcontrol
  namespace: "proj-gr4"
spec:
  selector:
    app: accountingcontrol
  ports:
    - port: 8080
      targetPort: 80
  type: LoadBalancer
    
      
      
