---
apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  annotations: 
  name: grp4-mongodb-pvc
  namespace: proj-gr4
spec:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: "mongodb"
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata: 
  annotations: 
  labels:
    app: mongodb
  name: mongodb
  namespace: proj-gr4
spec:
  ports:
    - port: 8022
      targetPort: 27017
  selector:
    app: mongodb
---  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: "proj-gr4"
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - image: mongo
        name: mongodb
        resources:
          limits:
            memory: 2Gi
          requests:
            memory: 1Gi
        volumeMounts:
        - mountPath: "data/db"
          name: "mongodb-data"
      volumes:
      - name: "mongodb-data"
        persistentVolumeClaim: 
          claimName: "grp4-mongodb-pvc"
---